# Generated by Django 2.2.28 on 2023-07-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230718_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asdasdas',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
