# Generated by Django 2.2.28 on 2023-07-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_asdasdas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='asdasdas',
        ),
    ]
